river: river.c
	$(CC) -c list.c -Wall -Wextra -pedantic -std=c99
	$(CC) -c river.c -Wall -Wextra -pedantic -std=c99
	$(CC) river.o list.o -o river  -Wall -Wextra -pedantic -std=c99
clean:
	rm list.o river.o river
